spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/trains?createDatabaseIfNotExist=true


logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.sql.BasicBinder: TRACE
#    org.springframework.security: TRACE
