trains-core:
  url: "http://localhost:8090"

logging:
  level:
    org.springframework.security: TRACE

auth-server:
  url: "http://localhost:8080"

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
