server:
  port: 9010

management:
  server:
    port: 9011
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
spring:
  application:
    name: trains-api

    # Enable virtual threads
  threads:
    virtual:
      enabled: true



trains-core:
  url: http://${CORE_URL}:${CORE_PORT}

auth-server:
  url: http://${AUTH_URL}:${AUTH_SERVER_PORT}

# disable swagger ui in production
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
